spring:
  application:
    # Eureka한테 나의 이름을 알려주기 위해 이름 설정
    name: member-service # configs 레포에 만들었던 yml 파일과 이름이 일치해야 한다.
  config:
    import: "optional:configserver:http://localhost:8888/"
    fail-fast: true # 얘는 중요한 건 아니다. config 서버가 실패하면 빠르게 실패로 판단하겠다는 설정